# SPDX-FileCopyrightText: 2025 Mads R. Havmand <mads@v42.dk>
#
# SPDX-License-Identifier: AGPL-3.0-only

[tools]
"aqua:google/osv-scanner" = "2.0.2"
buf = "1.54.0"
"go:golang.org/x/tools/cmd/deadcode" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
golangci-lint = "2.1.6"
grpcurl = "1.9.3"
node = "24.2.0"
"npm:@anthropic-ai/claude-code" = "1.0.65"
"npm:@bufbuild/protoc-gen-es" = "2.6.1"
"pipx:reuse" = "latest"
protoc-gen-connect-go = "1.18.0"
protoc-gen-go = "1.36.6"
shellcheck = "0.10.0"
"ubi:CycloneDX/cyclonedx-gomod" = "1.9.0"
go = "1.24.4"
python = "3.12.11"
"go:github.com/mrjoshuak/godoc-mcp" = "latest"
"npm:prettier" = "3.6.2"
goreleaser = "2.11.1"
cosign = "2.5.3"
jq = "1.8.0"

[task_config]
includes = ["scripts"]

[env]
_.path = ['{{config_root}}/frontend/node_modules/.bin']
