# SPDX-FileCopyrightText: 2025 Mads R. Havmand <mads@v42.dk>
#
# SPDX-License-Identifier: AGPL-3.0-only

[tools]
buf = "latest"
"go:golang.org/x/tools/cmd/deadcode" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
golangci-lint = "latest"
grpcurl = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "1.0.22"
"npm:@bufbuild/protoc-gen-es" = "2.5.2"
"npm:@connectrpc/protoc-gen-connect-es" = "1.6.1"
"pipx:reuse" = "latest"
protoc-gen-connect-go = "latest"
protoc-gen-go = "latest"
shellcheck = "latest"
"ubi:CycloneDX/cyclonedx-gomod" = "latest"

[task_config]
includes = ["scripts"]

[env]
_.path = ['{{config_root}}/frontend/node_modules/.bin']
